### PR TITLE
Added license to package.json

### PR DESCRIPTION
**Pull request by spalger**
I see that it's listed in the README, but this helps computers know the license too.

### CODE REVIEW

**Comment by cbas** [comment]
This would be quite helpful for tools like [nlf](https://www.npmjs.com/package/nlf).

@jfhbrook Are you able to accept this PR and publish to npm?

**Comment by jfhbrook** [comment]
@spalger @cbas I just fixed this, the package has a LICENSE file in it now.

**Comment by jfhbrook** [comment]
Sorry, didn't realize these were actually 2 separate issues.

Thanks!

**Comment by spalger** [comment]
:+1:

**Pull request merged**
